export const ELEMENTS ={
    edit1:'tr:nth-child(1) a:nth-child(1)',
    delete1:'tr:nth-child(1) a+ a',
    edit2:'tr:nth-child(2) a:nth-child(1)',
    delete2:'tr:nth-child(2) a+ a',
    edit3:'tr:nth-child(3) a:nth-child(1)',
    delete3:'tr:nth-child(3) a+ a',
    edit4:'tr:nth-child(4) a:nth-child(1)',
    delete4:'tr:nth-child(4) a+ a',
    edit5:'tr:nth-child(5) a:nth-child(1)',
    delete5:'tr:nth-child(5) a+ a',
    edit6:'tr:nth-child(6) a:nth-child(1)',
    delete6:'tr:nth-child(6) a+ a',
    edit7:'tr:nth-child(7) a:nth-child(1)',
    delete7:'tr:nth-child(7) a+ a',
    edit8:'tr:nth-child(8) a:nth-child(1)',
    delete8:'tr:nth-child(8) a+ a',
    edit9:'tr:nth-child(9) a:nth-child(1)',
    delete9:'tr:nth-child(9) a+ a',
    edit10:'tr:nth-child(10) a:nth-child(1)',
    delete10:'tr:nth-child(10) a+ a',
}